MSeifert04/iteration_utilities

src_c/reducefirst.c
tests/test_itertools_cfuncs.py

Add additional kwargs to first function

---

docs/index.rst
iteration_utilities/_recipes/_core.py
src_c/module.c
src_c/recipesroundrobin.c
tests/historical_roundrobin.py
tests/test_itertools_cfuncs.py
tests/test_itertools_recipes.py

C Function Roundrobin

---

src_c/reduceminmax.c
tests/helper_leak.py
tests/test_itertools_cfuncs.py

check for all memory leaks

---

src_c/recipesmerge.c
tests/test_itertools_cfuncs.py

Allow pickling for merge function

---

src_c/recipessuccessive.c

include INCREF in setstate of successive

---

src_c/recipesgrouper.c
src_c/recipesmerge.c
src_c/recipesroundrobin.c
src_c/recipessuccessive.c
src_c/reduceminmax.c
tests/test_itertools_cfuncs.py

Fix asserts c

---

tests/test_itertools_cfuncs.py

include some missing memory leak tests

---

src_c/recipesgrouper.c

removed unnecessary inline comment

---

docs/index.rst
src_c/module.c
src_c/reducealldistinct.c
tests/test_itertools_cfuncs.py

C Function: all_distinct

---

src_c/recipesuniquejust.c
tests/test_unique_justseen.py

Similar to #73 but I already deleted the old branch 😞

removed Fallback if EQ fails in unique_justseen (unpythonic!)

---

src_c/functionscompose.c
src_c/mathematical.c
src_c/module.c
tests/test_compose.py

added "double" mathematical function.

added "reverse" and "all" keyword for compose class.

---

.travis.yml
MANIFEST.in
appveyor.yml
docs/generators.rst
iteration_utilities/core.py
src_c/_module.c
src_c/recipesclamp.c
tests/test_clamp.py

C Function: clamp

---

docs/generators.rst
iteration_utilities/_recipes/_additional.py
iteration_utilities/_recipes/_core.py
iteration_utilities/core.py
tests/test__python_cls.py
tests/test__python_funcs.py

For new functions/classes:
include it in the ``__init__`` of the python module?
Examples?

Some additional functions based on chain and islice to mimic list methods

---

docs/reduce.rst
iteration_utilities/_recipes/_additional.py
iteration_utilities/_recipes/_core.py
iteration_utilities/core.py
src_c/recipesapplyfunc.c
tests/test__python_funcs.py
tests/test_applyfunc.py

removed take function (in favor of getitem and list) and some doc changes

---

docs/generators.rst
iteration_utilities/core.py
src_c/_globaldocs.c
src_c/_module.c
src_c/functionschained.c
src_c/functionscomplement.c
src_c/functionsconst.c
src_c/functionsflip.c
src_c/functionsnth.c
src_c/recipesaccumulate.c
src_c/recipesapplyfunc.c
src_c/recipesclamp.c
src_c/recipesdeepflatten.c
src_c/recipesduplicates.c
src_c/recipesgrouper.c
src_c/recipesintersperse.c
src_c/recipesiterexcept.c
src_c/recipesmerge.c
src_c/recipesroundrobin.c
src_c/recipessplit.c
src_c/recipessuccessive.c
src_c/recipesuniquejust.c
tests/test_duplicates.py

For new functions/classes:
include it in the ``__init__`` of the python module?
Examples?

C Function: duplicates

---

docs/reduce.rst
iteration_utilities/core.py
src_c/_module.c
src_c/reduceallmonotone.c
tests/test_allmonotone.py

For new functions/classes:
include it in the ``__init__`` of the python module?
Examples?

C Function: all_monotone

---

docs/operators.rst
src_c/_module.c
src_c/mathematical.c

For new functions/classes:
include it in the ``__init__`` of the python module?
Examples?

Added reverse floordiv and modulo operator

---

docs/index.rst
docs/misc.rst
src_c/_helper.c
src_c/_helperitemidxkey.c
src_c/_module.c
src_c/recipesmerge.c
tests/test_itemidxkey.py
tests/test_merge.py

Create own ItemIdxKey class for merge

---

docs/index.rst

Fix redirecting link, not a big change.

Update moved more-itertools link

---

docs/CHANGES.rst
src/nth.c
tests/test_nth.py

Segfault in nth

---

docs/CHANGES.rst
src/clamp.c
tests/test_clamp.py

In case remove=False or neither low nor high are given the length hint can be determined.

Length_hint for clamp

---

src/_helper.c

Makes the functions TupleCopy, TupleInsert and TupleRemove more aligned.
Also speeds up `TupleReversed` by making get and set index loop variables (this only affects `Flip`).

refactored some helper functions

---

docs/CHANGES.rst
src/chained.c
tests/test_chained.py

Check if the functions given to chained.__new__ contain other "chained" instances.

---

docs/CHANGES.rst
src/_itemidxkey.c
src/_seen.c
src/deepflatten.c
tests/helper_cls.py
tests/test_deepflatten.py

Check for errors when using PyObject_IsInstance or avoid it

---

docs/generated/InfiniteIterable.rst
docs/generated/Iterable.rst
docs/generated/replicate.rst

- length_hint and getitem for Iterable
- getitem for InfiniteIterable
- autoclass instead of autofunction for replicate

Documentation related changes:

---

docs/CHANGES.rst
src/accumulate.c
src/clamp.c
src/deepflatten.c
src/grouper.c
src/intersperse.c
src/merge.c
src/replicate.c
src/roundrobin.c
src/sideeffect.c
src/successive.c
tests/helper_cls.py
tests/test_accumulate.py
tests/test_clamp.py
tests/test_grouper.py
tests/test_intersperse.py
tests/test_merge.py
tests/test_replicate.py
tests/test_roundrobin.py
tests/test_sideeffects.py
tests/test_successive.py

Check return of PyObject_LengthHint and test for overflow

---

setup.cfg

Add extra requires in setup.cfg

---

.github/workflows/test.yml

Test against rc1 of Python 3.8

---

tests/test__c_funcs.py

Test tp_traverse implementations

---

tests/test_partial.py

Fix StackOverflow that sometimes happens in partial test recursive pickle
